# Python 开发环境搭建 {#ide}

## 在 Windows 中安装 Python 3

Python 支持多个平台，其中在 Mac、类 UNIX 平台中已默认安装，Windows 平台中的安装也非常简单，从官方网站下载安装包安装即可，注意安装完成后将 Python 所在目录添加到系统路径（PATH）中。

## 在 MacOS 中安装 Python 3

在目前的 MacOS 中，内置的 Python 版本为 2.7。如果要安装 Python3，步骤如下：

### 安装 Xcode

在终端中运行如下命令：

```bash
xcode-select --install
```

### 安装 Homebrew

在终端中运行如下命令：

```bash
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

Homebrew 安装完后，使用 vim 或者其他编辑器将如下内容添加到`~/.profile`文件中。

```bash
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
```

### 安装 Python3

在终端中运行如下指令：

```bash
brew install python3
```

### 使用 Python3

使用 Homebrew 安装 Python3 后，系统就有两个 Python 环境，如果要使用系统自带的 Python2
，则使用如下指令：

```bash
python
```

而如果要使用 Python3，则使用如下指令：

```bash
python3
```

## 使用 python 虚拟环境

### 为什么要用虚拟环境

虽然使用 python3 这样的工具，能够使用 python3 解释器，但在开发人员需要在不同的版本中安装扩展包时，或者在需要使用不同版本的某个解释器、扩展包时，如果只使用系统唯一的开发环境，就显得捉襟见肘。

### 虚拟环境的创建与使用

因此，Python 提供了创建虚拟环境的工具`venv`，例如：

```bash
python3.7 -m venv python37
```

上面的命令将在当前目录中创建名为`python37`的目录，其中参数`-m`的作用是让后面的库以脚本的形式运行（-mod）。进入该目录后，再运行：

```bash
source bin/activate
```

就会激活该虚拟环境，命令后会出现`(python37)`这样的提示符。

在该目录中运行`deactivate`则会退出虚拟环境。

### 虚拟环境与系统环境的区别

使用 venv 命令创建的虚拟环境是一个独立于系统 Python 目录的轻量级 Python 目录，虚拟环境目录和系统 Python 目录之间共享的是 Python 标准库，而每个虚拟目录各自拥有独立的 Python 扩展以及各自的 pip 包管理，如果系统有多个版本的 Python 主库，也可以基于其自身创建不同版本的 Python 虚拟环境。

在一个虚拟环境中，只能有一个版本的 Python。而在系统环境中，可以有多个版本的 Pyhton。

## 编辑器

虽然 Python 自带编辑器，但其不够方便，推荐使用轻量级的编辑器 Sublime Text 或者 Visual Studio Code。使用编辑器将文件保存成`.py`后缀，然后通过命令行调用即可执行。

如在编辑器中键入如下内容：

```python
print("hello world")
```

保存为`hello.py`（文件名不能与 Python 的各种函数、库名相同），注意设置文件编码方式为`UTF-8`。

启动终端，进入到脚本所在路径，执行：

```bash
python hello.py
```

即可看到运行结果。

### Visual Studio Code 中的必要设置

使用 Visual Studio Code 作为 Python 开发编辑器，最好进行如下操作：

1. 安装 Python 扩展。
1. 安装语法提示插件。
1. 选择解释器。当 Visual Studio Code 遇到 Python 虚拟环境的时候时常会无法找到正确的 Python 解释器和虚拟环境，导致调试无法进行。
   解决的方案是：选择 Visual Studio Code 的设置菜单，在工作目录（workspace）中，正确设置`python.pythonPath`的值，这样可以避免项目之间发生版本冲突。
